/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/__root"
import { Route as SpecializationsRouteImport } from "./routes/specializations"
import { Route as ServicesRouteImport } from "./routes/services"
import { Route as RequestQuoteRouteImport } from "./routes/request-quote"
import { Route as ProjectsRouteImport } from "./routes/projects"
import { Route as ProductsRouteImport } from "./routes/products"
import { Route as ContactRouteImport } from "./routes/contact"
import { Route as AboutRouteImport } from "./routes/about"
import { Route as IndexRouteImport } from "./routes/index"
import { Route as ServicesIndexRouteImport } from "./routes/services.index"
import { Route as SpecializationsSlugRouteImport } from "./routes/specializations.$slug"
import { Route as ServicesServiceSlugRouteImport } from "./routes/services.$serviceSlug"
import { Route as ProductsCategorySlugRouteImport } from "./routes/products.$categorySlug"
import { Route as ProductsCategorySlugProductSlugRouteImport } from "./routes/products.$categorySlug.$productSlug"

const SpecializationsRoute = SpecializationsRouteImport.update({
  id: "/specializations",
  path: "/specializations",
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: "/services",
  path: "/services",
  getParentRoute: () => rootRouteImport,
} as any)
const RequestQuoteRoute = RequestQuoteRouteImport.update({
  id: "/request-quote",
  path: "/request-quote",
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsRoute = ProjectsRouteImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRoute = ProductsRouteImport.update({
  id: "/products",
  path: "/products",
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: "/contact",
  path: "/contact",
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: "/about",
  path: "/about",
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => ServicesRoute,
} as any)
const SpecializationsSlugRoute = SpecializationsSlugRouteImport.update({
  id: "/$slug",
  path: "/$slug",
  getParentRoute: () => SpecializationsRoute,
} as any)
const ServicesServiceSlugRoute = ServicesServiceSlugRouteImport.update({
  id: "/$serviceSlug",
  path: "/$serviceSlug",
  getParentRoute: () => ServicesRoute,
} as any)
const ProductsCategorySlugRoute = ProductsCategorySlugRouteImport.update({
  id: "/$categorySlug",
  path: "/$categorySlug",
  getParentRoute: () => ProductsRoute,
} as any)
const ProductsCategorySlugProductSlugRoute =
  ProductsCategorySlugProductSlugRouteImport.update({
    id: "/$productSlug",
    path: "/$productSlug",
    getParentRoute: () => ProductsCategorySlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/contact": typeof ContactRoute
  "/products": typeof ProductsRouteWithChildren
  "/projects": typeof ProjectsRoute
  "/request-quote": typeof RequestQuoteRoute
  "/services": typeof ServicesRouteWithChildren
  "/specializations": typeof SpecializationsRouteWithChildren
  "/products/$categorySlug": typeof ProductsCategorySlugRouteWithChildren
  "/services/$serviceSlug": typeof ServicesServiceSlugRoute
  "/specializations/$slug": typeof SpecializationsSlugRoute
  "/services/": typeof ServicesIndexRoute
  "/products/$categorySlug/$productSlug": typeof ProductsCategorySlugProductSlugRoute
}
export interface FileRoutesByTo {
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/contact": typeof ContactRoute
  "/products": typeof ProductsRouteWithChildren
  "/projects": typeof ProjectsRoute
  "/request-quote": typeof RequestQuoteRoute
  "/specializations": typeof SpecializationsRouteWithChildren
  "/products/$categorySlug": typeof ProductsCategorySlugRouteWithChildren
  "/services/$serviceSlug": typeof ServicesServiceSlugRoute
  "/specializations/$slug": typeof SpecializationsSlugRoute
  "/services": typeof ServicesIndexRoute
  "/products/$categorySlug/$productSlug": typeof ProductsCategorySlugProductSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  "/": typeof IndexRoute
  "/about": typeof AboutRoute
  "/contact": typeof ContactRoute
  "/products": typeof ProductsRouteWithChildren
  "/projects": typeof ProjectsRoute
  "/request-quote": typeof RequestQuoteRoute
  "/services": typeof ServicesRouteWithChildren
  "/specializations": typeof SpecializationsRouteWithChildren
  "/products/$categorySlug": typeof ProductsCategorySlugRouteWithChildren
  "/services/$serviceSlug": typeof ServicesServiceSlugRoute
  "/specializations/$slug": typeof SpecializationsSlugRoute
  "/services/": typeof ServicesIndexRoute
  "/products/$categorySlug/$productSlug": typeof ProductsCategorySlugProductSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | "/"
    | "/about"
    | "/contact"
    | "/products"
    | "/projects"
    | "/request-quote"
    | "/services"
    | "/specializations"
    | "/products/$categorySlug"
    | "/services/$serviceSlug"
    | "/specializations/$slug"
    | "/services/"
    | "/products/$categorySlug/$productSlug"
  fileRoutesByTo: FileRoutesByTo
  to:
    | "/"
    | "/about"
    | "/contact"
    | "/products"
    | "/projects"
    | "/request-quote"
    | "/specializations"
    | "/products/$categorySlug"
    | "/services/$serviceSlug"
    | "/specializations/$slug"
    | "/services"
    | "/products/$categorySlug/$productSlug"
  id:
    | "__root__"
    | "/"
    | "/about"
    | "/contact"
    | "/products"
    | "/projects"
    | "/request-quote"
    | "/services"
    | "/specializations"
    | "/products/$categorySlug"
    | "/services/$serviceSlug"
    | "/specializations/$slug"
    | "/services/"
    | "/products/$categorySlug/$productSlug"
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  ProductsRoute: typeof ProductsRouteWithChildren
  ProjectsRoute: typeof ProjectsRoute
  RequestQuoteRoute: typeof RequestQuoteRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SpecializationsRoute: typeof SpecializationsRouteWithChildren
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/specializations": {
      id: "/specializations"
      path: "/specializations"
      fullPath: "/specializations"
      preLoaderRoute: typeof SpecializationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/services": {
      id: "/services"
      path: "/services"
      fullPath: "/services"
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/request-quote": {
      id: "/request-quote"
      path: "/request-quote"
      fullPath: "/request-quote"
      preLoaderRoute: typeof RequestQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/projects": {
      id: "/projects"
      path: "/projects"
      fullPath: "/projects"
      preLoaderRoute: typeof ProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/products": {
      id: "/products"
      path: "/products"
      fullPath: "/products"
      preLoaderRoute: typeof ProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/contact": {
      id: "/contact"
      path: "/contact"
      fullPath: "/contact"
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/about": {
      id: "/about"
      path: "/about"
      fullPath: "/about"
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/": {
      id: "/"
      path: "/"
      fullPath: "/"
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    "/services/": {
      id: "/services/"
      path: "/"
      fullPath: "/services/"
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    "/specializations/$slug": {
      id: "/specializations/$slug"
      path: "/$slug"
      fullPath: "/specializations/$slug"
      preLoaderRoute: typeof SpecializationsSlugRouteImport
      parentRoute: typeof SpecializationsRoute
    }
    "/services/$serviceSlug": {
      id: "/services/$serviceSlug"
      path: "/$serviceSlug"
      fullPath: "/services/$serviceSlug"
      preLoaderRoute: typeof ServicesServiceSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    "/products/$categorySlug": {
      id: "/products/$categorySlug"
      path: "/$categorySlug"
      fullPath: "/products/$categorySlug"
      preLoaderRoute: typeof ProductsCategorySlugRouteImport
      parentRoute: typeof ProductsRoute
    }
    "/products/$categorySlug/$productSlug": {
      id: "/products/$categorySlug/$productSlug"
      path: "/$productSlug"
      fullPath: "/products/$categorySlug/$productSlug"
      preLoaderRoute: typeof ProductsCategorySlugProductSlugRouteImport
      parentRoute: typeof ProductsCategorySlugRoute
    }
  }
}

interface ProductsCategorySlugRouteChildren {
  ProductsCategorySlugProductSlugRoute: typeof ProductsCategorySlugProductSlugRoute
}

const ProductsCategorySlugRouteChildren: ProductsCategorySlugRouteChildren = {
  ProductsCategorySlugProductSlugRoute: ProductsCategorySlugProductSlugRoute,
}

const ProductsCategorySlugRouteWithChildren =
  ProductsCategorySlugRoute._addFileChildren(ProductsCategorySlugRouteChildren)

interface ProductsRouteChildren {
  ProductsCategorySlugRoute: typeof ProductsCategorySlugRouteWithChildren
}

const ProductsRouteChildren: ProductsRouteChildren = {
  ProductsCategorySlugRoute: ProductsCategorySlugRouteWithChildren,
}

const ProductsRouteWithChildren = ProductsRoute._addFileChildren(
  ProductsRouteChildren,
)

interface ServicesRouteChildren {
  ServicesServiceSlugRoute: typeof ServicesServiceSlugRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesServiceSlugRoute: ServicesServiceSlugRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface SpecializationsRouteChildren {
  SpecializationsSlugRoute: typeof SpecializationsSlugRoute
}

const SpecializationsRouteChildren: SpecializationsRouteChildren = {
  SpecializationsSlugRoute: SpecializationsSlugRoute,
}

const SpecializationsRouteWithChildren = SpecializationsRoute._addFileChildren(
  SpecializationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  ProductsRoute: ProductsRouteWithChildren,
  ProjectsRoute: ProjectsRoute,
  RequestQuoteRoute: RequestQuoteRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SpecializationsRoute: SpecializationsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
